name: Calendar Share (Secure)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  calendar_share_secure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Create token.pickle
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: |
          echo "$GOOGLE_TOKEN" | base64 --decode > token.pickle

      - name: Decrypt processed_events.pkl
        env:
          EVENTS_ENCRYPTION_KEY: ${{ secrets.EVENTS_ENCRYPTION_KEY }}
        run: |
          if [ -f processed_events.pkl.enc ]; then
            openssl enc -aes-256-cbc -d -pbkdf2 -in processed_events.pkl.enc -out processed_events.pkl -pass pass:"$EVENTS_ENCRYPTION_KEY"
          else
            echo "No encrypted file found, first run."
          fi

      - name: Run calendar_share.py
        run: python calendar_share.py

      - name: Encrypt processed_events.pkl
        env:
          EVENTS_ENCRYPTION_KEY: ${{ secrets.EVENTS_ENCRYPTION_KEY }}
        run: |
          openssl enc -aes-256-cbc -salt -pbkdf2 -in processed_events.pkl -out processed_events.pkl.enc -pass pass:"$EVENTS_ENCRYPTION_KEY"

      - name: Commit encrypted file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update encrypted processed_events"
          file_pattern: 'processed_events.pkl.enc'
